version: "2"
linters:
  default: none
  enable:
    - staticcheck
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-ST1003"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
        - "-SA1019"
        - "-QF1008"
