port: 7882

rtc:
  port_range_start: 60000
  port_range_end: 64000
  tcp_port: 7883
  use_external_ip: false
  use_ice_lite: true
  use_mdns: false
  stun_servers:
    - stun.l.google.com:19302
    - stun.l.google.com:5349
    - stun1.l.google.com:3478
  relay:
    udp_port: 4445
    tcp_port: 0
    port_range_start: 5000
    port_range_end: 5999
    use_external_ip: false
    use_ice_lite: true
    use_mdns: false
    force_tcp: false

bind_addresses:
  - 0.0.0.0

prometheus_port: 6788

solana:
  wallet_private_key: "3DariyNEUpStnoXMCjR2EgQXfobq3AQsWM4nVQKrbpv47XKiboXovWfQdsb6uUGPbuTb5gkYQFCpvJ71vAxDoJL4"
  contract_address: "E2FcHsC9STeB6FEtxBKGAwMTX7cbfYMyjSHKs4QbBAmh"
  network_host_http: "https://api.devnet.solana.com"
  network_host_ws: "wss://api.devnet.solana.com/"
  registry_authority: "8bxabQhCLRfpHZQjAXg9AmqqyQ2WJrXQVAQXH3YFzxwT"

p2p:
  peer_listen_port: 3500
  database_name: "livekit_global"

log_level: debug
logging:
  pion_level: trace