# main TCP port for RoomService and RTC endpoint
# for production setups, this port should be placed behind a load balancer with TLS
port: 7880

# log level, valid values: debug, info, warning, error
log_level: info

# when redis is set, LiveKit will automatically operate in a fully distributed fashion
# clients could connect to any node and be routed to the same room
redis:
  address: redis.host:6379
#  username: myuser
#  password: mypassword

# when enabled, LiveKit will expose prometheus metrics on :6789/metrics
#prometheus_port: 6789

# WebRTC configuration
rtc:
  # the main UDP port to transport WebRTC data
  udp_port: 9000
  # when set, LiveKit enable WebRTC ICE over TCP when UDP isn't available
  # this port *cannot* be behind load balancer or TLS, and must be exposed on the node
  # WebRTC transports are encrypted and do not require additional encryption
  tcp_port: 7881
  # when set to true, attempts to discover the host's public IP via STUN
  # this is useful for cloud environments such as AWS, where hosts have an internal IP
  # that maps to an external one
  use_external_ip: true
  # optional settings
#  # when using REMB, the max bitrate that the SFU would accept, defaults to 3Mbps
#  max_bitrate: 3145728
#  # number of packets to buffer in the SFU, defaults to 500
#  packet_buffer_size: 500
#  # optional stun servers to use. by default LiveKit uses Google's public STUN servers
#  # LiveKit will automatically configure connected clients to use the same STUN servers
#  stun_servers:
#    - server1
#  # minimum amount of time between pli/fir rtcp packets being sent to an individual
#  # producer. Increasing these times can lead to longer black screens when participants join,
#  # while reducing them can lead to higher producer bitrates.
#  pli_throttle:
#    low_quality: 1s
#    mid_quality: 2s
#    high_quality: 3s


# API key / secret pairs.
# Keys are used for JWT authentication, server APIs would require a keypair in order to generate access tokens
# and make calls to the server
keys:
  key1: secret1
  key2: secret2

# customize audio level sensitivity
#audio:
#  # minimum level to be considered active, 0-127, where 0 is loudest
#  # defaults to 40
#  active_level: 40
#  # percentile to measure, a participant is considered active if it has exceeded the
#  # ActiveLevel more than MinPercentile% of the time
#  # defaults to 15
#  min_percentile: 15
#  # frequency in ms to notify changes to clients, defaults to 500
#  update_interval: 500
#  # to prevent speaker updates from too jumpy, smooth out values over N samples
#  smooth_samples: 5

# turn server
turn:
  # Uses TLS. Requires cert and key pem files by one of:
  # - using turn.mount_path and turn.secretName if deploying with our helm chart
  # - LIVEKIT_TURN_CERT and LIVEKIT_TURN_KEY env vars with file locations
  # - using cert_file and key_file below
  # defaults to false
  enabled: false
  # needs to match tls cert domain
  domain: turn.livekit.io
  # defaults to 3478
  tls_port: 3478
  # optional
  # cert_file: /path/to/cert.pem
  # key_file: /path/to/key.pem
