#cloud-config
write_files:
  - path: /opt/livekit-server/config.yaml
    content: |
      log_level: info
      port: 7880
      rtc:
        use_external_ip: true
        tcp_port: 7881
        udp_port: 7882
      keys:
        APIkey1: secret1
  - path: /opt/livekit-server/ssl/server.crt
    content: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
  - path: /opt/livekit-server/ssl/server.key
    content: |
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----

runcmd:
  - export LIVEKIT_VERSION=v0.13 # LiveKit Docker image tag
  - systemctl enable docker.livekit-server@${LIVEKIT_VERSION}
  - systemctl start docker.livekit-server@${LIVEKIT_VERSION}
  - systemctl restart nginx