#cloud-config
write_files:
  - path: /opt/livekit-server/config.yaml
    content: |
      keys:
        key1: secret1

runcmd:
  - export LIVEKIT_IMAGE_VERSION=v0.13 # set LiveKit version
  - systemctl enable docker.livekit-server@${LIVEKIT_IMAGE_VERSION}
  - systemctl start docker.livekit-server@${LIVEKIT_IMAGE_VERSION}
