#cloud-config
repo_update: true
repo_upgrade: all

packages:
  - docker

bootcmd:
  - mkdir /opt/livekit-server
  - mkdir -p /etc/nginx/conf.d/
  - mkdir -p /etc/pki/nginx/private

write_files:
  - path: /opt/livekit-server/config.yaml
    content: |
      log_level: info
      keys:
        key1: secret1
  - path: /etc/nginx/conf.d/livekit.conf
    content: |
      server {
        listen       443 ssl http2;
        listen       [::]:443 ssl http2;

        ssl_certificate "/etc/pki/nginx/livekit.crt";
        ssl_certificate_key "/etc/pki/nginx/private/livekit.key";

        location / {
          proxy_pass      http://127.0.0.1:7880;
        }
      }
  - path: /etc/pki/nginx/livekit.crt
    content: |
      <SSL CERT GOES HERE>
  - path: /etc/pki/nginx/private/livekit.key
    content: |
      <SSL KEY GOES HERE>

runcmd:
  - export LIVEKIT_VERSION=v0.13 # set LiveKit version
  - curl -o /etc/systemd/system/docker.livekit-server@.service -O https://raw.githubusercontent.com/livekit/livekit-server/master/deploy/docker.livekit-server%40.service
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable docker.livekit-server@${LIVEKIT_VERSION}
  - systemctl start docker.livekit-server@${LIVEKIT_VERSION}
  - amazon-linux-extras install -y nginx1
  - systemctl enable nginx
  - systemctl start nginx
