#cloud-config
write_files:
  - path: /opt/livekit-server/config.yaml
    content: |
      log_level: info
      keys:
        key1: secret1
  - path: /etc/pki/nginx/livekit.crt
    content: |
      <SSL CERT GOES HERE>
  - path: /etc/pki/nginx/private/livekit.key
    content: |
      <SSL KEY GOES HERE>

runcmd:
  - export LIVEKIT_VERSION=v0.13 # LiveKit Docker image tag
  - systemctl enable docker.livekit-server@${LIVEKIT_VERSION}
  - systemctl start docker.livekit-server@${LIVEKIT_VERSION}
  - systemctl reload nginx