#cloud-config
package_update: true
package_upgrade: all

packages:
  - docker.io
  - nginx

bootcmd:
  - mkdir /opt/livekit-server

write_files:
  - path: /opt/livekit-server/config.yaml
    content: |
      log_level: info
      keys:
        key1: secret1
  - path: /etc/nginx/sites-available/livekit
    content: |
      server {
        listen       443 ssl http2;
        listen       [::]:443 ssl http2;

        ssl_certificate "/etc/ssl/cert/livekit.crt";
        ssl_certificate_key "/etc/ssl/private/livekit.key";

        location / {
          proxy_pass      http://127.0.0.1:7880;
        }
      }
  - path: /etc/ssl/cert/livekit.crt
    content: |
      <SSL CERT GOES HERE>
  - path: /etc/ssl/private/livekit.key
    content: |
      <SSL KEY GOES HERE>

runcmd:
  - export LIVEKIT_VERSION=v0.13 # set LiveKit version
  - curl -o /etc/systemd/system/docker.livekit-server@.service -O https://raw.githubusercontent.com/livekit/livekit-server/master/deploy/docker.livekit-server%40.service
  - systemctl enable docker.livekit-server@${LIVEKIT_VERSION}
  - systemctl start docker.livekit-server@${LIVEKIT_VERSION}
  - ln -s /etc/nginx/sites-available/livekit /etc/nginx/sites-enabled/livekit
  - systemctl reload nginx
