#cloud-config
package_update: true
package_upgrade: all

packages:
  - docker.io

bootcmd:
  - mkdir /opt/livekit-server

write_files:
  - path: /opt/livekit-server/config.yaml
    content: |
      log_level: info
      keys:
        key1: secret1

runcmd:
  - export LIVEKIT_VERSION=v0.13 # LiveKit Docker image tag
  - curl -o /etc/systemd/system/docker.livekit-server@.service -O https://raw.githubusercontent.com/livekit/livekit-server/master/deploy/docker.livekit-server%40.service
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable docker.livekit-server@${LIVEKIT_VERSION}
  - systemctl start docker.livekit-server@${LIVEKIT_VERSION}
