// Code generated by counterfeiter. DO NOT EDIT.
package servicefakes

import (
	"context"
	"sync"
	"time"

	"github.com/livekit/livekit-server/pkg/service"
	"github.com/livekit/protocol/livekit"
)

type FakeTokenRevocationStore struct {
	GetRevocationCutoffStub        func(context.Context, livekit.RoomName, livekit.ParticipantIdentity) (time.Time, error)
	getRevocationCutoffMutex       sync.RWMutex
	getRevocationCutoffArgsForCall []struct {
		arg1 context.Context
		arg2 livekit.RoomName
		arg3 livekit.ParticipantIdentity
	}
	getRevocationCutoffReturns struct {
		result1 time.Time
		result2 error
	}
	getRevocationCutoffReturnsOnCall map[int]struct {
		result1 time.Time
		result2 error
	}
	RevokeTokensBeforeStub        func(context.Context, livekit.RoomName, livekit.ParticipantIdentity, time.Time, time.Duration) error
	revokeTokensBeforeMutex       sync.RWMutex
	revokeTokensBeforeArgsForCall []struct {
		arg1 context.Context
		arg2 livekit.RoomName
		arg3 livekit.ParticipantIdentity
		arg4 time.Time
		arg5 time.Duration
	}
	revokeTokensBeforeReturns struct {
		result1 error
	}
	revokeTokensBeforeReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTokenRevocationStore) GetRevocationCutoff(arg1 context.Context, arg2 livekit.RoomName, arg3 livekit.ParticipantIdentity) (time.Time, error) {
	fake.getRevocationCutoffMutex.Lock()
	ret, specificReturn := fake.getRevocationCutoffReturnsOnCall[len(fake.getRevocationCutoffArgsForCall)]
	fake.getRevocationCutoffArgsForCall = append(fake.getRevocationCutoffArgsForCall, struct {
		arg1 context.Context
		arg2 livekit.RoomName
		arg3 livekit.ParticipantIdentity
	}{arg1, arg2, arg3})
	stub := fake.GetRevocationCutoffStub
	fakeReturns := fake.getRevocationCutoffReturns
	fake.recordInvocation("GetRevocationCutoff", []interface{}{arg1, arg2, arg3})
	fake.getRevocationCutoffMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTokenRevocationStore) GetRevocationCutoffCallCount() int {
	fake.getRevocationCutoffMutex.RLock()
	defer fake.getRevocationCutoffMutex.RUnlock()
	return len(fake.getRevocationCutoffArgsForCall)
}

func (fake *FakeTokenRevocationStore) GetRevocationCutoffCalls(stub func(context.Context, livekit.RoomName, livekit.ParticipantIdentity) (time.Time, error)) {
	fake.getRevocationCutoffMutex.Lock()
	defer fake.getRevocationCutoffMutex.Unlock()
	fake.GetRevocationCutoffStub = stub
}

func (fake *FakeTokenRevocationStore) GetRevocationCutoffArgsForCall(i int) (context.Context, livekit.RoomName, livekit.ParticipantIdentity) {
	fake.getRevocationCutoffMutex.RLock()
	defer fake.getRevocationCutoffMutex.RUnlock()
	argsForCall := fake.getRevocationCutoffArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeTokenRevocationStore) GetRevocationCutoffReturns(result1 time.Time, result2 error) {
	fake.getRevocationCutoffMutex.Lock()
	defer fake.getRevocationCutoffMutex.Unlock()
	fake.GetRevocationCutoffStub = nil
	fake.getRevocationCutoffReturns = struct {
		result1 time.Time
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenRevocationStore) GetRevocationCutoffReturnsOnCall(i int, result1 time.Time, result2 error) {
	fake.getRevocationCutoffMutex.Lock()
	defer fake.getRevocationCutoffMutex.Unlock()
	fake.GetRevocationCutoffStub = nil
	if fake.getRevocationCutoffReturnsOnCall == nil {
		fake.getRevocationCutoffReturnsOnCall = make(map[int]struct {
			result1 time.Time
			result2 error
		})
	}
	fake.getRevocationCutoffReturnsOnCall[i] = struct {
		result1 time.Time
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenRevocationStore) RevokeTokensBefore(arg1 context.Context, arg2 livekit.RoomName, arg3 livekit.ParticipantIdentity, arg4 time.Time, arg5 time.Duration) error {
	fake.revokeTokensBeforeMutex.Lock()
	ret, specificReturn := fake.revokeTokensBeforeReturnsOnCall[len(fake.revokeTokensBeforeArgsForCall)]
	fake.revokeTokensBeforeArgsForCall = append(fake.revokeTokensBeforeArgsForCall, struct {
		arg1 context.Context
		arg2 livekit.RoomName
		arg3 livekit.ParticipantIdentity
		arg4 time.Time
		arg5 time.Duration
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.RevokeTokensBeforeStub
	fakeReturns := fake.revokeTokensBeforeReturns
	fake.recordInvocation("RevokeTokensBefore", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.revokeTokensBeforeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTokenRevocationStore) RevokeTokensBeforeCallCount() int {
	fake.revokeTokensBeforeMutex.RLock()
	defer fake.revokeTokensBeforeMutex.RUnlock()
	return len(fake.revokeTokensBeforeArgsForCall)
}

func (fake *FakeTokenRevocationStore) RevokeTokensBeforeCalls(stub func(context.Context, livekit.RoomName, livekit.ParticipantIdentity, time.Time, time.Duration) error) {
	fake.revokeTokensBeforeMutex.Lock()
	defer fake.revokeTokensBeforeMutex.Unlock()
	fake.RevokeTokensBeforeStub = stub
}

func (fake *FakeTokenRevocationStore) RevokeTokensBeforeArgsForCall(i int) (context.Context, livekit.RoomName, livekit.ParticipantIdentity, time.Time, time.Duration) {
	fake.revokeTokensBeforeMutex.RLock()
	defer fake.revokeTokensBeforeMutex.RUnlock()
	argsForCall := fake.revokeTokensBeforeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeTokenRevocationStore) RevokeTokensBeforeReturns(result1 error) {
	fake.revokeTokensBeforeMutex.Lock()
	defer fake.revokeTokensBeforeMutex.Unlock()
	fake.RevokeTokensBeforeStub = nil
	fake.revokeTokensBeforeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeTokenRevocationStore) RevokeTokensBeforeReturnsOnCall(i int, result1 error) {
	fake.revokeTokensBeforeMutex.Lock()
	defer fake.revokeTokensBeforeMutex.Unlock()
	fake.RevokeTokensBeforeStub = nil
	if fake.revokeTokensBeforeReturnsOnCall == nil {
		fake.revokeTokensBeforeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.revokeTokensBeforeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeTokenRevocationStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTokenRevocationStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.TokenRevocationStore = new(FakeTokenRevocationStore)
