name: Docker
on:
  workflow_dispatch:
  push:
    branches: [master, main, dev, test]
    tags: ['v*.*.*']
permissions:
  contents: read
  packages: write
jobs:
  docker:
    uses: hanzoai/.github/.github/workflows/docker-build.yml@main
    with:
      image: ghcr.io/hanzoai/livekit
      pre-build-command: |
        go mod download
        go install github.com/magefile/mage@latest
        mage generate
    secrets: inherit
