name: Release

on:
  workflow_dispatch:
  push:
    # only publish on version tags
    tags:
      - 'dz*.*.*'
    branches: [ devex ]

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Fetch all tags
        run: git fetch --force --tags
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
            ~/.cache
          key: livekit-server

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
