// Code generated by protoc-gen-psrpc v0.2.2, DO NOT EDIT.
// source: pkg/service/rpc/ingress.proto

package rpc

import context "context"

import psrpc1 "github.com/livekit/psrpc"

// ================================
// IngressInternal Client Interface
// ================================

type IngressInternalClient interface {
	ListActiveIngress(context.Context, *ListActiveIngressRequest, ...psrpc1.RequestOption) (<-chan *psrpc1.Response[*ListActiveIngressResponse], error)
}

// ====================================
// IngressInternal ServerImpl Interface
// ====================================

type IngressInternalServerImpl interface {
	ListActiveIngress(context.Context, *ListActiveIngressRequest) (*ListActiveIngressResponse, error)
}

// ================================
// IngressInternal Server Interface
// ================================

type IngressInternalServer interface {
	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// ======================
// IngressInternal Client
// ======================

type ingressInternalClient struct {
	client *psrpc1.RPCClient
}

// NewIngressInternalClient creates a psrpc client that implements the IngressInternalClient interface.
func NewIngressInternalClient(clientID string, bus psrpc1.MessageBus, opts ...psrpc1.ClientOption) (IngressInternalClient, error) {
	rpcClient, err := psrpc1.NewRPCClient("IngressInternal", clientID, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &ingressInternalClient{
		client: rpcClient,
	}, nil
}

func (c *ingressInternalClient) ListActiveIngress(ctx context.Context, req *ListActiveIngressRequest, opts ...psrpc1.RequestOption) (<-chan *psrpc1.Response[*ListActiveIngressResponse], error) {
	return psrpc1.RequestMulti[*ListActiveIngressResponse](ctx, c.client, "ListActiveIngress", "", req, opts...)
}

// ======================
// IngressInternal Server
// ======================

type ingressInternalServer struct {
	svc IngressInternalServerImpl
	rpc *psrpc1.RPCServer
}

// NewIngressInternalServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewIngressInternalServer(serverID string, svc IngressInternalServerImpl, bus psrpc1.MessageBus, opts ...psrpc1.ServerOption) (IngressInternalServer, error) {
	s := psrpc1.NewRPCServer("IngressInternal", serverID, bus, opts...)

	var err error
	err = psrpc1.RegisterHandler(s, "ListActiveIngress", "", svc.ListActiveIngress, nil)
	if err != nil {
		s.Close(false)
		return nil, err
	}

	return &ingressInternalServer{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *ingressInternalServer) Shutdown() {
	s.rpc.Close(false)
}

func (s *ingressInternalServer) Kill() {
	s.rpc.Close(true)
}

// ===============================
// IngressHandler Client Interface
// ===============================

type IngressHandlerClient interface {
	HangUpIngress(context.Context, string, *HangUpIngressRequest, ...psrpc1.RequestOption) (*HangUpIngressResponse, error)
}

// ===================================
// IngressHandler ServerImpl Interface
// ===================================

type IngressHandlerServerImpl interface {
	HangUpIngress(context.Context, *HangUpIngressRequest) (*HangUpIngressResponse, error)
}

// ===============================
// IngressHandler Server Interface
// ===============================

type IngressHandlerServer interface {
	RegisterHangUpIngressTopic(string) error
	DeregisterHangUpIngressTopic(string)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// =====================
// IngressHandler Client
// =====================

type ingressHandlerClient struct {
	client *psrpc1.RPCClient
}

// NewIngressHandlerClient creates a psrpc client that implements the IngressHandlerClient interface.
func NewIngressHandlerClient(clientID string, bus psrpc1.MessageBus, opts ...psrpc1.ClientOption) (IngressHandlerClient, error) {
	rpcClient, err := psrpc1.NewRPCClient("IngressHandler", clientID, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &ingressHandlerClient{
		client: rpcClient,
	}, nil
}

func (c *ingressHandlerClient) HangUpIngress(ctx context.Context, topic string, req *HangUpIngressRequest, opts ...psrpc1.RequestOption) (*HangUpIngressResponse, error) {
	return psrpc1.RequestSingle[*HangUpIngressResponse](ctx, c.client, "HangUpIngress", topic, req, opts...)
}

// =====================
// IngressHandler Server
// =====================

type ingressHandlerServer struct {
	svc IngressHandlerServerImpl
	rpc *psrpc1.RPCServer
}

// NewIngressHandlerServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewIngressHandlerServer(serverID string, svc IngressHandlerServerImpl, bus psrpc1.MessageBus, opts ...psrpc1.ServerOption) (IngressHandlerServer, error) {
	s := psrpc1.NewRPCServer("IngressHandler", serverID, bus, opts...)

	return &ingressHandlerServer{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *ingressHandlerServer) RegisterHangUpIngressTopic(topic string) error {
	return psrpc1.RegisterHandler(s.rpc, "HangUpIngress", topic, s.svc.HangUpIngress, nil)
}

func (s *ingressHandlerServer) DeregisterHangUpIngressTopic(topic string) {
	s.rpc.DeregisterHandler("HangUpIngress", topic)
}

func (s *ingressHandlerServer) Shutdown() {
	s.rpc.Close(false)
}

func (s *ingressHandlerServer) Kill() {
	s.rpc.Close(true)
}

var psrpcFileDescriptor1 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0xc8, 0x4e, 0xd7,
	0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2f, 0x2a, 0x48, 0xd6, 0xcf, 0xcc, 0x4b, 0x2f,
	0x4a, 0x2d, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0x48, 0x96, 0xe2,
	0xcd, 0x2f, 0x28, 0xc9, 0xcc, 0xcf, 0x83, 0x8a, 0x29, 0x49, 0x71, 0x49, 0xf8, 0x64, 0x16, 0x97,
	0x38, 0x26, 0x97, 0x64, 0x96, 0xa5, 0x7a, 0x42, 0x94, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97,
	0x28, 0xd9, 0x70, 0x49, 0x62, 0x91, 0x2b, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x92, 0xe7, 0xe2,
	0x86, 0x9a, 0x1e, 0x9f, 0x99, 0x52, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x19, 0xc4, 0x05, 0x15,
	0xf2, 0x4c, 0x29, 0x56, 0x12, 0xe3, 0x12, 0xf1, 0x48, 0xcc, 0x4b, 0x0f, 0x2d, 0x40, 0x33, 0x55,
	0x9c, 0x4b, 0x14, 0x4d, 0x1c, 0x62, 0xa2, 0x51, 0x2e, 0x17, 0x3f, 0x54, 0xc8, 0x33, 0xaf, 0x24,
	0xb5, 0x28, 0x2f, 0x31, 0x47, 0x28, 0x8a, 0x4b, 0x10, 0xc3, 0x05, 0x42, 0xb2, 0x7a, 0x45, 0x05,
	0xc9, 0x7a, 0xb8, 0x5c, 0x2d, 0x25, 0x87, 0x4b, 0x1a, 0x62, 0x8d, 0x12, 0xdb, 0xa6, 0x4e, 0x46,
	0x26, 0x0e, 0x46, 0xa3, 0x04, 0x2e, 0x3e, 0xa8, 0x94, 0x47, 0x62, 0x5e, 0x4a, 0x4e, 0x6a, 0x91,
	0x90, 0x1f, 0x17, 0x2f, 0x8a, 0xcb, 0x84, 0x24, 0xc1, 0x46, 0x61, 0xf3, 0x85, 0x94, 0x14, 0x36,
	0x29, 0x64, 0x1b, 0x24, 0x18, 0x9d, 0x74, 0xa2, 0xb4, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4,
	0x92, 0xf3, 0x73, 0xf5, 0x73, 0x32, 0xcb, 0x52, 0xb3, 0x33, 0x4b, 0xe0, 0x34, 0x5a, 0x5c, 0x25,
	0xb1, 0x81, 0x23, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xad, 0x04, 0x14, 0xe9, 0xc5, 0x01,
	0x00, 0x00,
}
